### ISSUE TITLE
unified dof-cubesat schema not building

### ISSUE THREAD

**Issue by Venkat4real** [ODU-CGA-CubeSat/cubesat-cli#4]
![image](https://github.com/ODU-CGA-CubeSat/cubesat-cli/assets/96865121/ba25a46b-f09e-4cf4-9eda-319991be39fc)

**Comment by capsulecorplab** [comment]
should be fixed as of gradle refactor https://github.com/ODU-CGA-CubeSat/cubesat-cli/commit/e0b000ccfbd0761a3abe3590eb2fc7f643efed05. Please reopen if this issue still persists
